# Form implementation generated from reading ui file 'menuPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindowInmobilaria(object):
    def setupUi(self, MainWindowInmobilaria):
        MainWindowInmobilaria.setObjectName("MainWindowInmobilaria")
        MainWindowInmobilaria.resize(800, 543)
        MainWindowInmobilaria.setStyleSheet("background-color:rgb(219, 227, 238);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindowInmobilaria)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 641, 391))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./vista/EmpresaLogo-removebg-preview.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindowInmobilaria.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindowInmobilaria)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(parent=self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindowInmobilaria.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindowInmobilaria)
        self.statusbar.setObjectName("statusbar")
        MainWindowInmobilaria.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindowInmobilaria)
        self.toolBar.setMovable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindowInmobilaria.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionAgregar = QtGui.QAction(parent=MainWindowInmobilaria)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("..\\vista\\AgregarUsuarios.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionAgregar.setIcon(icon)
        self.actionAgregar.setObjectName("actionAgregar")
        self.actionContratos = QtGui.QAction(parent=MainWindowInmobilaria)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("..\\vista\\Contratos.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionContratos.setIcon(icon1)
        self.actionContratos.setObjectName("actionContratos")
        self.actionSalir = QtGui.QAction(parent=MainWindowInmobilaria)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("..\\vista\\Salir.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionSalir.setIcon(icon2)
        self.actionSalir.setObjectName("actionSalir")
        self.actionReportes = QtGui.QAction(parent=MainWindowInmobilaria)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("..\\vista\\Reportes.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionReportes.setIcon(icon3)
        self.actionReportes.setObjectName("actionReportes")
        self.menuMenu.addAction(self.actionAgregar)
        self.menuMenu.addAction(self.actionReportes)
        self.menuMenu.addAction(self.actionContratos)
        self.menuMenu.addAction(self.actionSalir)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.toolBar.addAction(self.actionAgregar)
        self.toolBar.addAction(self.actionContratos)
        self.toolBar.addAction(self.actionReportes)
        self.toolBar.addAction(self.actionSalir)

        self.retranslateUi(MainWindowInmobilaria)
        QtCore.QMetaObject.connectSlotsByName(MainWindowInmobilaria)

    def retranslateUi(self, MainWindowInmobilaria):
        _translate = QtCore.QCoreApplication.translate
        MainWindowInmobilaria.setWindowTitle(_translate("MainWindowInmobilaria", "::MainWindow::"))
        self.menuMenu.setTitle(_translate("MainWindowInmobilaria", "Menu"))
        self.toolBar.setWindowTitle(_translate("MainWindowInmobilaria", "toolBar"))
        self.actionAgregar.setText(_translate("MainWindowInmobilaria", "Agregar"))
        self.actionContratos.setText(_translate("MainWindowInmobilaria", "Contratos"))
        self.actionSalir.setText(_translate("MainWindowInmobilaria", "Salir"))
        self.actionReportes.setText(_translate("MainWindowInmobilaria", "Reportes"))
